### ISSUE TITLE
ngAnimate: the addClass/removeClass class is added during the animation

### ISSUE THREAD

**Issue by mzgol** [angular/angular.js#11810]
See http://plnkr.co/edit/iAgdX7hon6aEqMvSko9A?p=preview and click the green box while looking at its styles. The `addClass`/`removeClass`/`addClass-active`/`removeClass-active` class is being added during the animation. Is this intended? Note that HTML is case-insensitive so this looks weird.

Angular 1.4.0-rc.1.

![screen shot 2015-05-05 at 18 43 28](https://cloud.githubusercontent.com/assets/1758366/7477835/d0c12720-f356-11e4-8139-ba19b76bb7da.png)

cc @matsko

**Comment by mzgol** [comment]
For posterity:

JS:
```js
'use strict';

angular.module('myApp', ['ngAnimate', 'ngResource', 'ngSanitize'])
.directive('cbnItemPanel', function ($timeout) {
  return {
    restrict: 'E',
    template: '<div><div class="slider-trigger"></div></div>',
    scope: {
      ui: '=',
    },
    link: function (scope, elem) {
      elem.find('.slider-trigger').on('click', function () {
        scope.$apply(function () {
          console.log('click!');
          scope.ui.historyShown = !scope.ui.historyShown;
        });
      });
    },
  };
})
.run(function ($rootScope) {
  $rootScope.state = {
    ui: {
      historyShown: false,
    },
  };
});
```
HTML:
```html
<!DOCTYPE html>
<html class="ng-cloak" ng-app="myApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Test page</title>
  </head>

  <body>
    <cbn-item-panel
      ng-class="{
        'history-compensated-anim': state.ui.historyShown,
      }"
      ui="state.ui"></cbn-item-panel>
      
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <script src="https://code.angularjs.org/1.4.0-rc.1/angular.js"></script>
    <script src="https://code.angularjs.org/1.4.0-rc.1/angular-animate.js"></script>
    <script src="https://code.angularjs.org/1.4.0-rc.1/angular-resource.js"></script>
    <script src="https://code.angularjs.org/1.4.0-rc.1/angular-sanitize.js"></script>
    <link rel="stylesheet" href="style.css" />
    <script src="script.js"></script>
  </body>
</html>
```
CSS:
```css
cbn-item-panel {
  position: fixed;
  width: 100%;
  height: 100%;
  display: block;
  background-color: #2b2b2b;
}

cbn-item-panel.history-compensated-anim-add {
  transition: transform 3s;
  transform: translateY(0);
}

cbn-item-panel.history-compensated-anim,
cbn-item-panel.history-compensated-anim-add.history-compensated-anim-add-active {
  transform: translateY(54px);
}

cbn-item-panel.history-compensated-anim-remove {
  transition: transform 4s;
  transform: translateY(54px);
}

cbn-item-panel,
cbn-item-panel.history-compensated-anim-remove.history-compensated-anim-remove-active {
  transform: translateY(0);
}

.slider-trigger {
    position: relative;
    display: block;
    width: 100px;
    height: 30px;
    background: red;
}
```
