### ISSUE TITLE
ViewEncapsulation.Emulated breaks if certain attribute selectors (*= and ~=) are applied on the root element of a component

### ISSUE THREAD

**Issue by Honn** [angular/angular.js#13670]
Emulated view encapsulation can fail if there are any attribute selectors on the topmost element in the component (i.e. the element that will get the custom attribute that is used for encapsulation). The styles will be modified incorrectly if the attribute selector has a contains or contains word selector, so `*=` or `~=`.

Example:
Let's say we have a component with the selector `my-component`. It also has a custom attriute called `custom-attribute`. First a working case, using attribute equals.  
```css
my-component[custom-attribute="value"] {
	background-color: red;
}

# View encapsulation converts this to
my-component[custom-attribute="value"][_ngcontent-eod-X] {
	background-color: red;
}
```

In this case both the view encaptulation and the custom attribute selector will work as expected. However, lets use a contains selector instead (note the `*=` in the selector).

```css
my-component[custom-attribute*="value"] {
	background-color: red;
}

```

This time the view encapsulation gets confused and adds the new attribute in the middle of the selector!

```css
my-component[custom-attribute[_ngcontent-eod-X]*="value"] {
	background-color: red;
}
```

Needless to say this cases both the encaptulation and the attribute selector to fail. An easy way around is of course to wrap the insides of the component in a new element and have the custom attribute there, but this shouldn't really be needed.

Final note: It appears that the `^=` doesn't have this problem.
