### ISSUE TITLE
ng-animate 1.5.5 - ng-animate-ref - Cannot read property 'setHost' of undefined (angular-animate.js:3246)

### ISSUE THREAD

**Issue by jantimon** [angular/angular.js#14641]
**Steps to reproduce and a minimal demo of the problem**
Plunkr: http://plnkr.co/edit/rO7zneeJAWVNc4Ndck0i?p=preview

```css
.row.ng-anchor-in-add {
	// How long should the move IN take:
	transition: 0.5s linear all;
}
```

Steps to reproduce:

1. Click at **start**.

**Current behavior**

Javascript error: 

```
TypeError: Cannot read property 'setHost' of undefined
    at p (angular-animate.js:3246)
    at Array.d.push.fn (angular-animate.js:3078)
    at c (angular-animate.js:423)
    at b (angular-animate.js:393)
    at angular-animate.js:3087
    at n.$digest (angular.js:17123)
    at n.$apply (angular.js:17337)
    at HTMLAnchorElement.<anonymous> (angular.js:25023)
    at Qf (angular.js:3456)
    at HTMLAnchorElement.Pf.d (angular.js:3444)
```

**Expected/desired behavior**

Should start the ng-animate-ref animation

**Other information**

The bug occurs only if the following css lines are missing:

```css
.row.ng-leave {
	transition: 0.2s linear all;
}
```
