### ISSUE TITLE
Edge bug - print - hidden elements are visible 

### ISSUE THREAD

**Issue by Casimodo72** [angular/angular.js#15026]
Hi,

This is just an info and warning.
The Edge browser will not honor ng-show/ng-hide (and whatever they do) when printing a page subsequently.
This is not an AngularJS bug, because printing works fine in Chrome and Firefox.

We got hit by an Edge bug today. Well, actually for a month (?) already, but I only realized today why our users were sporadically reporting that our print-forms look really wrong sometimes.

E.g. we use Kendo UI Mobile with AngularJS. When we navigate to a page intended for printing, then only the *first* print rendering is correct. Any subsequent print of that page will incorrectly show hidden elements. This even occurs if we navigate away from that page, change the data and visit it again - Edge's print rendering (i.e. already visible in Edge's print preview) stays incorrect.

The known workaround for us is to refresh the page using the browser's refresh button. Then we are able to print that page again correctly for 1 single time.

See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7289494/

Regards
Kasimier Buchcik

**Comment by gkalpak** [comment]
All `ng-show/hide` do is add/remove a class (namely `ng-hide`). Angular associated a CSS style with the `ng-hide` class, that sets the element's `display` property to `none` (as long as the element is not animating, but that detail doesn't seem related to the issue). The rest is the browsers job. All this could be done by manually adding/removing the class or the CSS style.

It is not clear if this is bug with the browser, some 3rd-party library or the app itself. But there is definitely no indication that this is a issue with Angular, so I am going to close this.

<sub>(Happy to reopen and investigate if there info that indicates this is related to Angular.)</sub>

**Comment by jennings** [comment]
We ran into this issue, and we found that the problem is triggered by the selectors list that `.ng-hide` is a part of:

```css
[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate) {
    display:none !important;
}
```

The first selector is the one causing Edge's print rendering to break, it apparently doesn't apply the rule when the `[ng\:cloak]` selector is there.

Our workaround is to copy this rule into our own styles without the `[ng\:cloak]` selector:

```css
[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate) {
    display: none !important;
}
```
