### ISSUE TITLE
#chrome links with transition color issue

### ISSUE THREAD

**Issue by Ciul** [angular/angular.js#3164]
I'm passing an application to Angularjs, it is using Twitter Bootstrap.
And something strange is happening on Chrome.

I override links with next rule to make transition color and background:

``` css
a, a:visited, a:focus, a:hover, a:visited {
    -webkit-transition: all 0.5s linear;
    -moz-transition: all 0.5s linear;
    -ms-transition: all 0.5s linear;
    -o-transition: all 0.5s linear;
    transition: all 0.5s linear;
    text-decoration: none;
}
```

Now, there are some links that not taking initial color (white) that they should have, instead they're getting transparent.

This is fixed if:
1- I open or close the console (really strange)
2- After first hover over the links.
3- I modify the styles of anything else using the console

Also, this happens only in Google Chrome, not happening in FireFox, neither on IE.
And this happens only on the Angularjs version of the app.

If I remove the transitions styles they work as expected (having color white on initial state and not transparent).

http://screencast.com/t/ThnqK1kAdX
(left window is Chrome, right window is FireFox)

Any idea?
