### ISSUE TITLE
iOS CSS animation flicker ngAnimate

### ISSUE THREAD

**Issue by petalvlad** [angular/angular.js#8538]
Hey guys!

Has anybody experienced flicker effect like this?

![output_optimized](https://cloud.githubusercontent.com/assets/1518705/3857185/dd405dc0-1f00-11e4-8e9b-68d421101e5e.gif)

Without `ngAnimate` there is no flicker but I lose other needed animations using `ng-enter` and `ng-leave`. So I need to stay with `ngAnimate` but get rid of the flicker.

This is only iOS issue, on Desktop browsers everything works fine.

Initial state of popup:

``` css
.fade-scale {   
  -webkit-transition: all .2s ease-in-out;
  -webkit-transform:scale(0.8);
  opacity:0; 
}
```

On tap it adds this class on popup

``` css
.show {
  -webkit-transform:scale(1);
  opacity:1;      
}
```
