### ISSUE TITLE
ngAnimate transition bug when is apply to a TR.  

### ISSUE THREAD

**Issue by thierryc** [angular/angular.js#9462]
The display in .ng-hide-add-active and .ng-hide-remove transition is block !. 

Version : AngularJS v1.2.25

```css
.ng-hide-add-active, .ng-hide-remove {
	display: block !important;
}
```

I suggest to change it to table-row.

```css
tr.ng-hide-add-active, tr.ng-hide-remove {
	display: table-row !important;
}
```

 component: ngAnimate
